@startuml
digraph finite_state_machine {
  rankdir=LR;
  node [shape = doublecircle]; SETUP END;
  node [shape = circle];

  SETUP -> READY [ label = "READY" ]
  READY -> STARTUP [ label = "PLAY" ]

  STARTUP -> STARTUP [ label = "START_BUFFERING" ]
  STARTUP -> STARTUP [ label = "END_BUFFERING" ]
  STARTUP -> PLAYING [ label = "TIMECHANGED" ]

  PLAYING -> PLAYING [ label = "TIMECHANGED" ]
  PLAYING -> PLAYING [ label = "END_BUFFERING" ]
  PLAYING -> REBUFFERING [ label = "START_BUFFERING" ]
  REBUFFERING -> PLAYING [ label = "END_BUFFERING" ]
  REBUFFERING -> REBUFFERING [ label = "TIMECHANGED" ]

  PLAYING -> PAUSE [ label = "PAUSE" ]
  REBUFFERING -> PAUSE [ label = "PAUSE" ]
  PAUSE -> PLAYING [ label = "PLAY" ]

  PLAYING -> QUALITYCHANGE [ label = "VIDEO_CHANGE" ]
  PLAYING -> QUALITYCHANGE [ label = "AUDIO_CHANGE" ]
  QUALITYCHANGE -> QUALITYCHANGE [ label = "VIDEO_CHANGE" ]
  QUALITYCHANGE -> QUALITYCHANGE [ label = "AUDIO_CHANGE" ]
  QUALITYCHANGE -> PLAYING [ label = "TIMECHANGED" ]

  PAUSE -> QUALITYCHANGE_PAUSE [ label = "VIDEO_CHANGE" ]
  PAUSE -> QUALITYCHANGE_PAUSE [ label = "AUDIO_CHANGE" ]
  QUALITYCHANGE_PAUSE -> QUALITYCHANGE_PAUSE [ label = "VIDEO_CHANGE" ]
  QUALITYCHANGE_PAUSE -> QUALITYCHANGE_PAUSE [ label = "AUDIO_CHANGE" ]
  QUALITYCHANGE_PAUSE -> PAUSE [ label = "FINISH_QUALITYCHANGE_PAUSE" ]

  PAUSE -> PAUSED_SEEKING [ label = "SEEK" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "SEEK" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "AUDIO_CHANGE" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "VIDEO_CHANGE" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "START_BUFFERING" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "END_BUFFERING" ]
  PAUSED_SEEKING -> PAUSE [ label = "SEEKED" ]
  PAUSED_SEEKING -> PAUSED_SEEKING [ label = "PLAY" ]

  PAUSE -> PLAY_SEEKING [ label = "PLAY_SEEK" ]
  PAUSED_SEEKING -> PLAY_SEEKING [ label = "PLAY_SEEK" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "PLAY_SEEK" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "SEEK" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "AUDIO_CHANGE" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "VIDEO_CHANGE" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "START_BUFFERING" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "END_BUFFERING" ]
  PLAY_SEEKING -> PLAYING [ label = "SEEKED" ]
  PLAY_SEEKING -> PLAY_SEEKING [ label = "PLAY" ]

  PLAYING -> END [ label = "END" ]
  PAUSE -> END [ label = "END" ]

  SETUP -> ERROR [ label = "Error" ]
  READY -> ERROR [ label = "Error" ]
  STARTUP -> ERROR [ label = "Error" ]
  PLAYING -> ERROR [ label = "Error" ]
  REBUFFERING -> ERROR [ label = "Error" ]
  QUALITYCHANGE -> ERROR [ label = "Error" ]
  QUALITYCHANGE_PAUSE -> ERROR [ label = "Error" ]
  PAUSED_SEEKING -> ERROR [ label = "Error" ]
  SETUP -> ERROR [ label = "Error" ]
}
@enduml